# Input/output configuration
input_dir: /global/cscratch1/sd/xju/exatrkx/ITK/with_clustershape_ttbar/features_barrel_pixel
output_dir: /global/cscratch1/sd/xju/exatrkx/ITK/barrel_pixel_shape
project: BarrelPixelClusterShape
overwrite: True
sanity_steps: 0

# Dataset parameters
pt_signal_min: 0
pt_background_min: 0
n_hits: 0
primary_only: True
train_split: [[900, 20, 20]] # Number of [training, validation, testing] examples
true_edges: "layerless_true_edges"
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 9
emb_hidden: 512
nb_layer: [10]
emb_dim: 16
weight: 5
randomisation: 1
points_per_batch: 20000
r_train: 1.0
r_val: 1.7
r_test: 1.7
knn: [30]
knn_val: [40]
knn_test: [40]
warmup: 5000
margin: 1
lr: [0.0001]
factor: 0.3
patience: 50
regime: [[rp, hnm, ci]]
max_epochs: 10

callbacks: [[EmbeddingTelemetry, EmbeddingBuilder]]
wandb_save_dir: /global/cscratch1/sd/xju/exatrkx/ITK/wandb_data 
